- .gitignore
- Cargo.toml
- mistralrs-core/Cargo.toml
- mistralrs-core/src/models/gemma.rs
- mistralrs-core/src/models/llama.rs
- mistralrs-core/src/models/mistral.rs
- mistralrs-core/src/models/mixtral.rs
- mistralrs-core/src/models/quantized_llama.rs
- mistralrs-core/src/pipeline/gemma.rs
- mistralrs-core/src/pipeline/llama.rs
- mistralrs-core/src/pipeline/mistral.rs
- mistralrs-core/src/pipeline/mixtral.rs
- mistralrs-core/src/pipeline/mod.rs
- mistralrs-core/src/xlora_models/gemma.rs
- mistralrs-core/src/xlora_models/llama.rs
- mistralrs-core/src/xlora_models/mistral.rs
- mistralrs-core/src/xlora_models/mixtral.rs
- mistralrs-core/src/xlora_models/quantized_llama.rs
> Optimization: Add fused kernels

- mistralrs-core/src/pipeline/mod.rs
- mistralrs-server/src/main.rs
Currently the `mistralrs-server` always uses the `TokenSource::CacheToken` TokenSource which is a bit unintuitive, especially if i want to use it in a docker container. 
This PR allows the `TokenSource` to be defined via the cli as follows: 
- `CacheToken` (Default): Same as current behaviour
- `Literal`: `--token-source literal:hf_xxxxxxxxxxx` uses the provided token
- `EnvVar`: `--token-source env:ENV` uses the provided environment variable, if no variable is provided it defaults to `HUGGING_FACE_HUB_TOKEN`  (similar behaviour as TGI/TEI)
-  `Path`: `--token-source path:.\token` uses the provided path
> Server: Allow `TokenSource` to be configured via cli

- mistralrs-core/src/models/llama.rs
> Fix Llama contig error

- mistralrs-core/src/engine/mod.rs
- mistralrs-core/src/request.rs
- mistralrs-core/src/response.rs
- mistralrs-core/src/sequence.rs
- mistralrs-pyo3/src/lib.rs
- mistralrs-server/src/main.rs
> Initial setup for streaming

- ADDING_MODELS.md
- README.md
- mistralrs-core/src/models/gemma.rs
- mistralrs-core/src/models/llama.rs
- mistralrs-core/src/models/mistral.rs
- mistralrs-core/src/models/mixtral.rs
- mistralrs-core/src/models/mod.rs
- mistralrs-core/src/models/quantized_llama.rs
- mistralrs-core/src/xlora_models/gemma.rs
- mistralrs-core/src/xlora_models/llama.rs
- mistralrs-core/src/xlora_models/mistral.rs
- mistralrs-core/src/xlora_models/mixtral.rs
- mistralrs-core/src/xlora_models/quantized_llama.rs
Refs #75. Refactors redundant structs.
> Add guide for adding models

- mistralrs-server/src/main.rs
Closes #79 
```
$ curl -v http://localhost:1234/v1/chat/completions \
-H "Content-Type: application/json" \
-H "Authorization: Bearer EMPTY" \
-d '{
"model": "",
"messages": [
{
"role": "user",
"content": "Tell me a joke."
}
]
}'
*   Trying 127.0.0.1:1234...
* Connected to localhost (127.0.0.1) port 1234 (#0)
> POST /v1/chat/completions HTTP/1.1
> Host: localhost:1234
> User-Agent: curl/7.81.0
> Accept: */*
> Content-Type: application/json
> Authorization: Bearer EMPTY
> Content-Length: 89
> 
* Mark bundle as not supporting multiuse
< HTTP/1.1 200 OK
< content-type: application/json
< content-length: 509
< date: Sat, 06 Apr 2024 05:02:25 GMT
< 
* Connection #0 to host localhost left intact
{"id":"0","choices":[{"finish_reason":"stop","index":0,"message":{"content":"Why don't scientists …
```
> Fix OpenAI server response headers

- mistralrs-core/src/models/mistral.rs
- mistralrs-core/src/pipeline/mistral.rs
- mistralrs-core/src/xlora_models/mistral.rs
> Make mistral sliding window mask optional

- README.md
- examples/server/chat.py
- examples/server/streaming.py
- mistralrs-core/src/lib.rs
- mistralrs-core/src/models/mod.rs
- mistralrs-core/src/models/phi2.rs
- mistralrs-core/src/models/quantized_llama.rs
- mistralrs-core/src/pipeline/mod.rs
- mistralrs-core/src/pipeline/phi2.rs
- mistralrs-core/src/xlora_models/mod.rs
- mistralrs-core/src/xlora_models/phi2.rs
- mistralrs-core/src/xlora_models/quantized_llama.rs
- mistralrs-server/src/main.rs
- mistralrs-server/src/model_selected.rs
- mistralrs/src/lib.rs
Introduces use of candle_nn::RotaryEmbedding::new_partial for the phi partial RoPE.
> Implement Phi2 model

- mistralrs-core/src/models/quantized_llama.rs
- mistralrs-core/src/pipeline/llama.rs
- mistralrs-core/src/pipeline/mistral.rs
- mistralrs-core/src/pipeline/mixtral.rs
- mistralrs-core/src/xlora_models/quantized_llama.rs
> Get gguf context length from metadata

- mistralrs-lora/src/lib.rs
- mistralrs-lora/src/loralinear.rs
- mistralrs-lora/src/qloralinear.rs
In preparation for full LoRA support via merged layers to not degrade performance.
> Implement merging for Lora layers

- README.md
- examples/server/prompt.py
- integrations/llama_index_integration.py
- mistralrs-core/src/engine/mod.rs
- mistralrs-core/src/pipeline/mod.rs
- mistralrs-core/src/pipeline/phi2.rs
Refs #49.
Supports non instruction tuned models.
> Support no chat template

- Cargo.toml
- mistralrs-core/src/pipeline/gemma.rs
- mistralrs-core/src/pipeline/llama.rs
- mistralrs-core/src/pipeline/mistral.rs
- mistralrs-core/src/pipeline/mixtral.rs
- mistralrs-core/src/pipeline/mod.rs
- mistralrs-core/src/pipeline/phi2.rs
I did some profiling with https://github.com/mstange/samply/ and this took 10% of the hot loop on the profile.
This PR: ~66 tok/s Master: ~66 tok/s. I guess it overlapped with GPU work?
> Pre-calculate EOS token

- README.md
- mistralrs-server/src/main.rs
- mistralrs-server/src/prompt_mode.rs
> Implement a single prompt mode

- mistralrs-core/src/prefix_cacher.rs
> Fix prefix caching

- examples/server/chat.py
- examples/server/completion.py
- mistralrs-core/src/engine/mod.rs
- mistralrs-core/src/sequence.rs
> Remove stop from response

- mistralrs-server/src/main.rs
> Remove short prompt cli arg

- mistralrs-core/src/scheduler.rs
- mistralrs-core/src/sequence.rs
> Fix parallel decoding

- mistralrs-core/src/sampler.rs
> Optimize apply penalties

- mistralrs-core/src/utils/varbuilder_utils.rs
> Do not track gradients

- README.md
- mistralrs-core/src/engine/mod.rs
- mistralrs-core/src/models/llama.rs
- mistralrs-core/src/pipeline/gemma.rs
- mistralrs-core/src/pipeline/llama.rs
- mistralrs-core/src/pipeline/mistral.rs
- mistralrs-core/src/pipeline/mixtral.rs
- mistralrs-core/src/pipeline/mod.rs
- mistralrs-core/src/pipeline/phi2.rs
- mistralrs-core/src/prefix_cacher.rs
- mistralrs-core/src/sequence.rs
- mistralrs-core/src/xlora_models/llama.rs
Refs #177.
https://huggingface.co/meta-llama/Meta-Llama-3-8B
> Add Llama3 Support

- mistralrs-bench/src/main.rs
> Compute ± range

- mistralrs-bench/src/main.rs
> Allow multiple concurrency levels in bench

- mistralrs-core/src/models/gemma.rs
- mistralrs-core/src/pipeline/gemma.rs
- mistralrs-core/src/pipeline/mod.rs
- mistralrs-core/src/xlora_models/gemma.rs
> Fix the gemma models

- mistralrs-core/src/engine/mod.rs
- mistralrs-core/src/prefix_cacher.rs
- mistralrs-core/src/utils/mod.rs
> Evict prefix cache on error

- mistralrs-core/src/sequence.rs
Fixes for non granular scalings.
> Fix the sequence len calculation for xlora

- README.md
- mistralrs-bench/src/main.rs
- mistralrs-core/src/pipeline/ggml.rs
- mistralrs-core/src/pipeline/gguf.rs
- mistralrs-core/src/pipeline/macros.rs
- mistralrs-core/src/pipeline/mod.rs
- mistralrs-core/src/pipeline/normal.rs
- mistralrs-pyo3/src/lib.rs
- mistralrs-server/src/main.rs
- mistralrs/examples/grammar/main.rs
- mistralrs/examples/quantized/main.rs
- mistralrs/examples/simple/main.rs
https://users.rust-lang.org/t/pyo3-jupyter-debugging-setup/87855
> Better support for jupyter by silent loading

- README.md
- mistralrs-core/src/models/layers.rs
- mistralrs-core/src/models/mod.rs
- mistralrs-core/src/models/phi3.rs
- mistralrs-core/src/models/quantized_phi2.rs
- mistralrs-core/src/pipeline/loaders.rs
- mistralrs-core/src/xlora_models/phi3.rs
This will enable support for 128K models.
> Add Phi3 Scaled RoPE, for 128K

- mistralrs-bench/README.md
- mistralrs-bench/src/main.rs
> Add docs for mistralrs-bench

- README.md
- mistralrs-core/src/lib.rs
- mistralrs-core/src/models/mod.rs
- mistralrs-core/src/models/qwen2.rs
- mistralrs-core/src/pipeline/chat_template.rs
- mistralrs-core/src/pipeline/loaders.rs
- mistralrs-core/src/pipeline/mod.rs
- mistralrs-core/src/pipeline/normal.rs
> Add the Qwen2 models

- README.md
- mistralrs-core/src/model_selected.rs
- mistralrs-core/src/models/gemma.rs
- mistralrs-core/src/models/llama.rs
- mistralrs-core/src/models/mistral.rs
- mistralrs-core/src/models/mixtral.rs
- mistralrs-core/src/models/phi2.rs
- mistralrs-core/src/models/phi3.rs
- mistralrs-core/src/models/qwen2.rs
- mistralrs-core/src/pipeline/macros.rs
- mistralrs-core/src/pipeline/mod.rs
- mistralrs-core/src/xlora_models/gemma.rs
- mistralrs-core/src/xlora_models/llama.rs
- mistralrs-core/src/xlora_models/mistral.rs
- mistralrs-core/src/xlora_models/mixtral.rs
- mistralrs-core/src/xlora_models/phi2.rs
- mistralrs-core/src/xlora_models/phi3.rs
- mistralrs-pyo3/API.md
> Support local loading

- README.md
- docs/CHAT_TOK.md
- docs/CMD_LINE_DOCS.md
- docs/NON_GRANULAR.md
- examples/python/cookbook.ipynb
- mistralrs-core/src/model_selected.rs
- mistralrs-pyo3/API.md
> Improve documentation

- examples/llama_index/cookbook.ipynb
- examples/python/cookbook.ipynb
- mistralrs-pyo3/Cargo_template.toml
- mistralrs-pyo3/README.md
- mistralrs-pyo3/pyproject_template.toml
- mistralrs-pyo3/upload.py
This will make the python installation as simple as:
```
sudo apt install libssl-dev pkg-config
pip install mistralrs-cuda
```
> Prepare for PyPi uploading

- mistralrs-core/src/pipeline/macros.rs
> Fix api_dir_list! and show better error

- docs/ADAPTER_MODELS.md
> docs: update ADAPTER_MODELS.md

- mistralrs-bench/Cargo.toml
- mistralrs-bench/src/main.rs
- mistralrs-core/src/engine/mod.rs
- mistralrs-core/src/lib.rs
- mistralrs-core/src/request.rs
- mistralrs-core/src/sequence.rs
- mistralrs-core/src/utils/mod.rs
- mistralrs-pyo3/Cargo.toml
- mistralrs-pyo3/src/lib.rs
- mistralrs-pyo3/src/stream.rs
- mistralrs-server/src/chat_completion.rs
- mistralrs-server/src/completions.rs
- mistralrs-server/src/interactive_mode.rs
- mistralrs/Cargo.toml
- mistralrs/examples/grammar/main.rs
- mistralrs/examples/isq/main.rs
- mistralrs/examples/quantized/main.rs
- mistralrs/examples/simple/main.rs
Continuation of https://github.com/EricLBuehler/mistral.rs/pull/228
> Async channels

- Cargo.toml
- mistralrs-bench/src/main.rs
- mistralrs-core/src/aici/bintokens.rs
- mistralrs-core/src/engine/mod.rs
- mistralrs-core/src/pipeline/chat_template.rs
- mistralrs-core/src/pipeline/ggml.rs
- mistralrs-core/src/pipeline/gguf.rs
- mistralrs-core/src/pipeline/macros.rs
- mistralrs-core/src/pipeline/mod.rs
- mistralrs-core/src/pipeline/normal.rs
- mistralrs-core/src/sampler.rs
- mistralrs-pyo3/Cargo.toml
- mistralrs-pyo3/Cargo_template.toml
- mistralrs-pyo3/src/lib.rs
- mistralrs-server/src/completions.rs
- mistralrs-server/src/main.rs
Also enable logging for pyo3 bindings.
> Source bos, eos tokens from generation_config.json

- mistralrs-core/src/model_selected.rs
Fixes unintuitive behavior as described on the Discord.
> Fix short param conflict for LoRA

- mistralrs-core/src/layers.rs
- mistralrs-core/src/models/mistral.rs
- mistralrs-core/src/models/mixtral.rs
- mistralrs-core/src/models/phi3.rs
- mistralrs-core/src/models/quantized_phi3.rs
- mistralrs-core/src/models/qwen2.rs
- mistralrs-core/src/xlora_models/mistral.rs
- mistralrs-core/src/xlora_models/mixtral.rs
- mistralrs-core/src/xlora_models/phi3.rs
> Fix Causal Mask

- README.md
- mistralrs-core/src/pipeline/macros.rs
Improves the README and also makes some logging more verbose.
Refs #295.
> More verbose logging when loading locally

- Cargo.toml
Added "full" feature for tokio to fix missing crate issue
> fix bug with mistralrs cuda

- mistralrs-core/Cargo.toml
- mistralrs-core/src/engine/mod.rs
- mistralrs-core/src/lib.rs
- mistralrs-core/src/scheduler.rs
- mistralrs-core/src/sequence.rs
- mistralrs-server/src/main.rs
> Add terminate on next step handler via ctrlc

- mistralrs-core/src/models/llama.rs
I'm wondering if the part of using kv cache is wrong because of wrong indexing.
> bug fix: llama kv cache part

- mistralrs-core/src/pipeline/gguf.rs
> Print gguf metadata consistently

- mistralrs-core/Cargo.toml
- mistralrs-core/src/engine/mod.rs
- mistralrs-core/src/lib.rs
- mistralrs-server/Cargo.toml
- mistralrs-server/src/interactive_mode.rs
- mistralrs-server/src/main.rs
> Better handling of ctrlc

- .github/workflows/analysis.yaml
> Add analysis bot

- Cargo.toml
- mistralrs-core/Cargo.toml
- mistralrs-server/Cargo.toml
- mistralrs-server/src/interactive_mode.rs
> Fix the ctrlc handler

- .github/workflows/ci.yml
- README.md
- docs/ADDING_MODELS.md
- docs/CHAT_TOK.md
Refs #322. Improves docs, fixes links, and adds link checker to CI.
> Improve chat templates docs

- mistralrs-core/src/device_map.rs
> Set device to cpu if loading isq

- README.md
- mistralrs-bench/Cargo.toml
- mistralrs-bench/src/main.rs
- mistralrs-core/Cargo.toml
- mistralrs-core/src/engine/mod.rs
- mistralrs-core/src/lib.rs
- mistralrs-core/src/pipeline/ggml.rs
- mistralrs-core/src/pipeline/gguf.rs
- mistralrs-core/src/pipeline/mod.rs
- mistralrs-core/src/pipeline/normal.rs
- mistralrs-pyo3/Cargo.toml
- mistralrs-pyo3/Cargo_template.toml
- mistralrs-pyo3/src/lib.rs
- mistralrs-server/Cargo.toml
- mistralrs-server/src/main.rs
> Add a verbose mode

- mistralrs-core/src/pipeline/gguf_tokenizer.rs
> Allow default unigram unk token for GGUF

- mistralrs-core/src/device_map.rs
> Clamp n device layers to n model layers

- mistralrs-core/src/models/quantized_llama.rs
- mistralrs-core/src/models/quantized_phi2.rs
- mistralrs-core/src/utils/max_seq_len.rs
- mistralrs-core/src/utils/mod.rs
- mistralrs-core/src/xlora_models/quantized_llama.rs
Refs #375. This does manual subtyping for GGUF max seq len values.
> Manual subtyping for u32 in GGUF max seq len

- Cargo.toml
- mistralrs-bench/Cargo.toml
- mistralrs-pyo3/Cargo.toml
- mistralrs-pyo3/Cargo_template.toml
- mistralrs-pyo3/pyproject.toml
- mistralrs-pyo3/pyproject_template.toml
- mistralrs-pyo3/src/lib.rs
- mistralrs-server/Cargo.toml
- mistralrs/Cargo.toml
> Patch incorrect unwrap and bump version

- mistralrs-core/src/pipeline/isq.rs
- mistralrs-core/src/utils/progress.rs
- mistralrs-core/src/utils/varbuilder_utils.rs
> Fix metal loading issue by loading sequentially

- mistralrs-core/src/layers.rs
> Add fused bias linear layer with cublaslt

- docs/PHI3V.md
- mistralrs-core/src/vision_models/phi3.rs
Note: we should improve the code handling the dtype for ISQ, probably with macros.
> Phi 3 vision ISQ support

- mistralrs-core/src/models/quantized_phi3.rs
- mistralrs-core/src/xlora_models/quantized_phi3.rs
> Fix Phi-3 GGUF

- README.md
- docs/CHAT_TOK.md
- mistralrs-core/src/gguf/chat_template.rs
- mistralrs-core/src/gguf/mod.rs
- mistralrs-core/src/pipeline/chat_template.rs
- mistralrs-core/src/pipeline/ggml.rs
- mistralrs-core/src/pipeline/gguf.rs
- mistralrs-core/src/pipeline/macros.rs
- mistralrs-core/src/pipeline/mod.rs
- mistralrs-core/src/pipeline/normal.rs
- mistralrs-core/src/pipeline/paths.rs
- mistralrs-core/src/pipeline/vision.rs
- mistralrs-core/src/utils/gguf_metadata.rs
> Support chat template from GGUF

- Cargo.toml
- mistralrs-core/Cargo.toml
- mistralrs-pyo3/Cargo_template.toml
This will avoid breaking changes in the future.
> Lock candle version to commit

- mistralrs-core/src/pipeline/speculative.rs
> chore: update speculative.rs

- Cargo.toml
- README.md
- docs/PHI3V.md
- examples/python/cookbook.ipynb
- examples/python/phi3v_base64.py
- examples/python/phi3v_local_img.py
- examples/server/phi3v_base64.py
- examples/server/phi3v_local_img.py
- mistralrs-bench/Cargo.toml
- mistralrs-pyo3/Cargo.toml
- mistralrs-pyo3/Cargo_template.toml
- mistralrs-pyo3/README.md
- mistralrs-pyo3/pyproject.toml
- mistralrs-pyo3/pyproject_template.toml
- mistralrs-pyo3/src/lib.rs
- mistralrs-server/Cargo.toml
- mistralrs-server/src/chat_completion.rs
- mistralrs-server/src/main.rs
- mistralrs/Cargo.toml
- Add examples of using base64 encoded inputs
- Add credits to READMEs
> Fix Python deps, base64 impl, add examples

- docs/PHI3V.md
- mistralrs-bench/src/main.rs
- mistralrs-core/src/lib.rs
- mistralrs-core/src/pipeline/ggml.rs
- mistralrs-core/src/pipeline/gguf.rs
- mistralrs-core/src/pipeline/normal.rs
- mistralrs-core/src/pipeline/vision.rs
- mistralrs-core/src/utils/debug.rs
- mistralrs-pyo3/src/lib.rs
- mistralrs-server/src/main.rs
Resolves #358 by implementing it in an alternative way.
> Remove multiple tracing initializations and init outside of mistralrs-core

- mistralrs-core/src/utils/normal.rs
> Improve `Auto` dtype determination

- mistralrs-core/src/models/gemma.rs
- mistralrs-core/src/models/llama.rs
- mistralrs-core/src/models/mistral.rs
- mistralrs-core/src/models/mixtral.rs
- mistralrs-core/src/models/phi2.rs
- mistralrs-core/src/models/phi3.rs
- mistralrs-core/src/models/quantized_llama.rs
- mistralrs-core/src/models/quantized_phi2.rs
- mistralrs-core/src/models/quantized_phi3.rs
- mistralrs-core/src/models/qwen2.rs
- mistralrs-core/src/utils/progress.rs
- mistralrs-core/src/vision_models/phi3.rs
- mistralrs-core/src/xlora_models/gemma.rs
- mistralrs-core/src/xlora_models/llama.rs
- mistralrs-core/src/xlora_models/mistral.rs
- mistralrs-core/src/xlora_models/mixtral.rs
- mistralrs-core/src/xlora_models/phi2.rs
- mistralrs-core/src/xlora_models/phi3.rs
- mistralrs-core/src/xlora_models/quantized_llama.rs
- mistralrs-core/src/xlora_models/quantized_phi3.rs
> Progress bar and logging when loading repeating layers

- Cargo.lock
- Cargo.toml
- mistralrs-bench/Cargo.toml
- mistralrs-core/Cargo.toml
- mistralrs-core/src/pipeline/isq.rs
- mistralrs-pyo3/Cargo.toml
- mistralrs-pyo3/Cargo_template.toml
- mistralrs-pyo3/pyproject.toml
- mistralrs-pyo3/pyproject_template.toml
- mistralrs-server/Cargo.toml
- mistralrs/Cargo.toml
> Bump version to 0.1.24

- mistralrs/examples/gemma2/main.rs
- mistralrs/examples/gguf_locally/main.rs
- mistralrs/examples/grammar/main.rs
- mistralrs/examples/idefics2/main.rs
- mistralrs/examples/isq/main.rs
- mistralrs/examples/lora/main.rs
- mistralrs/examples/lora_activation/main.rs
- mistralrs/examples/phi3v/main.rs
- mistralrs/examples/quantized/main.rs
- mistralrs/examples/simple/main.rs
- mistralrs/examples/xlora/main.rs
> Select the best device in examples

- mistralrs/examples/gemma2/main.rs
- mistralrs/examples/gguf_locally/main.rs
- mistralrs/examples/grammar/main.rs
- mistralrs/examples/idefics2/main.rs
- mistralrs/examples/isq/main.rs
- mistralrs/examples/lora/main.rs
- mistralrs/examples/lora_activation/main.rs
- mistralrs/examples/phi3v/main.rs
- mistralrs/examples/quantized/main.rs
- mistralrs/examples/simple/main.rs
- mistralrs/examples/xlora/main.rs
> Use chat messages for the rust examples and show T/s

- mistralrs-core/src/pipeline/paths.rs
> chore: update paths.rs

- mistralrs-core/src/pipeline/mod.rs
- mistralrs-core/src/pipeline/vision.rs
- mistralrs-core/src/vision_models/idefics2.rs
- mistralrs-core/src/vision_models/phi3.rs
> Add AnyMoE support for vision models

- mistralrs-core/src/ops.rs
> Handle metal case for nonzero and bitwise ops

- Cargo.lock
- mistralrs-core/Cargo.toml
- mistralrs-core/src/aici/bintokens.rs
- mistralrs-core/src/aici/bytes.rs
- mistralrs-core/src/aici/cfg.rs
- mistralrs-core/src/aici/lex.rs
- mistralrs-core/src/aici/mod.rs
- mistralrs-core/src/aici/recognizer.rs
- mistralrs-core/src/aici/rx.rs
- mistralrs-core/src/aici/svob.rs
- mistralrs-core/src/aici/toktree.rs
- mistralrs-core/src/engine/mod.rs
- mistralrs-core/src/models/mod.rs
- mistralrs-core/src/models/starcoder2.rs
- mistralrs-core/src/pipeline/normal.rs
- mistralrs-core/src/pipeline/normal_loaders.rs
- mistralrs-core/src/pipeline/sampling.rs
- mistralrs-core/src/pipeline/speculative.rs
- mistralrs-core/src/xlora_models/mod.rs
- mistralrs-core/src/xlora_models/starcoder2.rs
> Implement the Starcoder 2 model architecture

- mistralrs-core/src/pipeline/paths.rs
- mistralrs-core/src/utils/varbuilder_utils.rs
@joshuasundance-swca adding it now, should make the [cognitivecomputations/dolphincoder-starcoder2-7b](https://huggingface.co/cognitivecomputations/dolphincoder-starcoder2-7b) model work!
> Support .bin, .pt, .pth extensions

- docs/PAGED_ATTENTION.md
- mistralrs-core/src/pipeline/macros.rs
- mistralrs-core/src/pipeline/mod.rs
- mistralrs-core/src/pipeline/vision.rs
- mistralrs-core/src/pipeline/vision_loaders.rs
- mistralrs-core/src/vision_models/idefics2.rs
- mistralrs-core/src/vision_models/llava/llava15.rs
- mistralrs-core/src/vision_models/llava/llava_llm/llama.rs
- mistralrs-core/src/vision_models/llava/llava_llm/mistral.rs
- mistralrs-core/src/vision_models/llava/llava_next.rs
- mistralrs-core/src/vision_models/mod.rs
- mistralrs-core/src/vision_models/phi3.rs
@haixuanTao this is that last thing to do before we can merge OpenVLA!
> Paged attention support for vision models

- docs/PAGED_ATTENTION.md
- mistralrs-bench/src/main.rs
- mistralrs-core/src/lib.rs
- mistralrs-core/src/utils/mod.rs
- mistralrs-paged-attn/build.rs
- mistralrs-pyo3/src/lib.rs
- mistralrs-server/src/main.rs
> Handle windows in paged attn build

- docs/ANYMOE.md
- mistralrs-core/Cargo.toml
> Add default plotly feature

- mistralrs-core/src/layers.rs
> Fix dtype with QLinear

- mistralrs-paged-attn/build.rs
This fixes compile issues with certain Nvidia drivers.
> Update paged-attn build.rs with NVCC flags

- mistralrs-core/src/xlora_models/classifier.rs
> Topk for X-LoRA scalings

- mistralrs-core/src/models/mixtral.rs
- mistralrs-core/src/pipeline/normal_loaders.rs
- mistralrs-core/src/xlora_models/mixtral.rs
I'm not a 100% sure, if this is actually this simple, but I tested it and it seems to be :)
- closes #615
> Make `sliding_window` optional for mixtral

- mistralrs-core/src/device_map.rs
- mistralrs-core/src/models/gemma.rs
- mistralrs-core/src/models/gemma2.rs
- mistralrs-core/src/models/llama.rs
- mistralrs-core/src/models/mistral.rs
- mistralrs-core/src/models/mixtral.rs
- mistralrs-core/src/models/phi2.rs
- mistralrs-core/src/models/phi3.rs
- mistralrs-core/src/models/qwen2.rs
- mistralrs-core/src/models/starcoder2.rs
- mistralrs-core/src/pipeline/normal.rs
- mistralrs-core/src/pipeline/vision.rs
- mistralrs-core/src/utils/normal.rs
- mistralrs-core/src/vision_models/llava/llava_llm/llama.rs
- mistralrs-core/src/vision_models/llava/llava_llm/mistral.rs
- mistralrs-core/src/vision_models/phi3.rs
- mistralrs-core/src/xlora_models/gemma.rs
- mistralrs-core/src/xlora_models/gemma2.rs
- mistralrs-core/src/xlora_models/llama.rs
- mistralrs-core/src/xlora_models/mistral.rs
- mistralrs-core/src/xlora_models/mixtral.rs
- mistralrs-core/src/xlora_models/phi2.rs
- mistralrs-core/src/xlora_models/phi3.rs
- mistralrs-core/src/xlora_models/starcoder2.rs
@chenwanqq This PR will resolve any issues with `to_dtype` copying causing OOM during loading.
> Rework the automatic dtype selection feature

- Cargo.lock
- Cargo.toml
- mistralrs-core/Cargo.toml
- mistralrs-core/src/models/llama.rs
- mistralrs-pyo3/Cargo_template.toml
@joshpopelka20 I merged your changes.
> Fix backend Candle fork Metal, flash attn, also Llama linear

- mistralrs-core/src/pipeline/loaders/mod.rs
- mistralrs-core/src/pipeline/loaders/normal_loaders.rs
- mistralrs-core/src/pipeline/loaders/vision_loaders.rs
- mistralrs-core/src/pipeline/mod.rs
- mistralrs-core/src/pipeline/normal.rs
- mistralrs-core/src/pipeline/vision.rs
Just a refactor. Cleans up `pipeline/mod.rs`.
> Refactor normal and vision loaders

- mistralrs-core/src/sampler.rs
> Using once_cell to reduce MSRV

- docs/PHI3.5MOE.md
- mistralrs-core/src/models/phi3_5_moe.rs
- mistralrs-core/src/pipeline/isq.rs
- Changing layer norm init to be more concise
- Do not ISQ gate layers
> Even more phi3.5moe fix attempts

- Cargo.lock
- Cargo.toml
- mistralrs-pyo3/Cargo.toml
- mistralrs-pyo3/Cargo_template.toml
- mistralrs-pyo3/src/lib.rs
- mistralrs-pyo3/src/util.rs
- mistralrs-server/Cargo.toml
> Add new parsing to Python API

- mistralrs-core/src/pipeline/amoe.rs
- mistralrs-core/src/pipeline/ggml.rs
- mistralrs-core/src/pipeline/gguf.rs
- mistralrs-core/src/pipeline/mod.rs
- mistralrs-core/src/pipeline/normal.rs
- mistralrs-core/src/pipeline/speculative.rs
- mistralrs-core/src/pipeline/vision.rs
Preparing for many new models:
- embedding models (Nomic planned!)
- text -> image (FLUX planned!)
- text -> speech (Parler TTS planned!)
- image -> text (BLIP planned!)
> Add the `ForwardInputsResult` api

- Cargo.lock
- Cargo.toml
- mistralrs-core/Cargo.toml
- mistralrs-pyo3/Cargo_template.toml
Credit to @sammcj, see EricLBuehler/candle#20.
> Fix f64-f32 type mismatch for Metal/Accelerate

- mistralrs-core/src/pipeline/gguf.rs
- mistralrs-core/src/pipeline/normal.rs
- mistralrs-core/src/pipeline/vision.rs
> Patch bug when not using PagedAttention

- Cargo.lock
- Cargo.toml
- mistralrs-core/Cargo.toml
- mistralrs-pyo3/Cargo_template.toml
> Fix Metal build error with seed

- mistralrs-core/src/engine/mod.rs
- mistralrs-core/src/model_loader.rs
- mistralrs-core/src/pipeline/ggml.rs
- mistralrs-core/src/pipeline/gguf.rs
- mistralrs-core/src/pipeline/normal.rs
- mistralrs-pyo3/src/lib.rs
> Fix and add checks for no kv cache

- mistralrs-core/src/vision_models/mllama/mod.rs
- mistralrs-core/src/vision_models/mllama/vision.rs
> Improved inverting for Attention Mask

- mistralrs-core/src/vision_models/mllama/mod.rs
Metal index select currently only works for floats.
> Fix `repeat_interleave`

- mistralrs-paged-attn/src/pagedattention.cu
> chore: update pagedattention.cu

- .typos.toml
- README.md
- docs/QUANTS.md
- mistralrs-quant/build.rs
- mistralrs-quant/kernels/marlin/marlin/marlin.cuh
- mistralrs-quant/kernels/marlin/marlin/marlin_dtypes.cuh
- mistralrs-quant/kernels/marlin/marlin_kernel.cu
- mistralrs-quant/src/gptq/cuda_backend.rs
- mistralrs-quant/src/gptq/ffi.rs
- mistralrs-quant/src/gptq/gptq_cpu.rs
- mistralrs-quant/src/gptq/gptq_cuda.rs
- mistralrs-quant/src/gptq/marlin_backend.rs
- mistralrs-quant/src/gptq/mod.rs
- mistralrs-quant/src/lib.rs
Increased speed on CUDA is to be expected.
> Add GPTQ Marlin support for 4 and 8 bit

- Cargo.lock
- Cargo.toml
- mistralrs-core/Cargo.toml
- mistralrs-core/src/attention.rs
- mistralrs-pyo3/Cargo_template.toml
Use some new MLX attention kernels!
Updated from mlx commit `f70764a`.
> Increase Metal decoding T/s by 26%

- Cargo.lock
- mistralrs-core/Cargo.toml
- mistralrs-core/src/aici/bintokens.rs
- mistralrs-core/src/gguf/gguf_tokenizer.rs
> Use tokenizers v0.20

- Cargo.lock
- Cargo.toml
- mistralrs-core/Cargo.toml
Doesn't look like we suffered any actual effects as k,v are both contiguous. However, this is a nice fix.
> Fix metal sdpa for v stride

- Cargo.lock
- Cargo.toml
- mistralrs-core/Cargo.toml
Increases prompt performance on Metal by *5.4x*
> Metal qmatmul mat-mat product (5.4x performance increase)

- Cargo.lock
- Cargo.toml
- mistralrs-core/Cargo.toml
Should improve CUDA compute cap support.
EricLBuehler/candle#42
> Dont always compile with fp8, bf16 for cuda

- mistralrs-core/src/attention.rs
Benefits CUDA, not really Metal.
> Default to SDPA for faster VLlama PP T/s

- mistralrs-core/src/pipeline/isq.rs
- mistralrs-core/src/pipeline/loaders/vision_loaders.rs
- mistralrs-core/src/vision_models/mllama/mod.rs
- mistralrs-core/src/vision_models/mllama/vision.rs
> VLlama vision model ISQ support

- Cargo.lock
- Cargo.toml
- mistralrs-core/Cargo.toml
> Support fp8 on Metal

- Cargo.lock
- Cargo.toml
- mistralrs-core/Cargo.toml
> Integrate fast MLX kernel for SDPA with long seqlen

- mistralrs-quant/build.rs
Should fix docker build errors.
> Use CUDA_COMPUTE_CAP if nvidia-smi not found

- mistralrs-core/src/pipeline/cache_manager.rs
> Fix append_sliding_window

- mistralrs-bench/src/main.rs
- mistralrs-core/src/engine/mod.rs
- mistralrs-core/src/lib.rs
- mistralrs-core/src/pipeline/amoe.rs
- mistralrs-core/src/request.rs
- mistralrs-core/src/sequence.rs
- mistralrs-pyo3/src/requests.rs
- mistralrs-server/src/openai.rs
Match openai behavior, see #955.
> Fix completion api behavior of best_of

- Cargo.lock
- mistralrs-core/Cargo.toml
> updated the tokenizers dependency of core to 0.21

- mistralrs-server/src/main.rs
Moves the creation of the `TcpListener` to the top of the `main` function to check for errors when binding to the address before loading the model. This avoids loading the model, which can take several minutes, when a bind error occurs.
> Fail fast on TcpListener bind errors

- Cargo.lock
- Cargo.toml
- mistralrs-core/Cargo.toml
- mistralrs-core/src/attention.rs
- mistralrs-core/src/vision_models/mllama/text.rs
- mistralrs-core/src/vision_models/mllama/vision.rs
- mistralrs-quant/src/bitsandbytes/op.rs
- mistralrs-quant/src/metal_kernels/mod.rs
- mistralrs-quant/src/utils/ops.rs
> Inplace softmax long-seqlen attention optimizations

- mistralrs-server/src/main.rs
This is to prevent the thread 'main' panicked at `mistralrs-server/src/main.rs` while use --interactive_mode or -i.
> fix mistralrs-server ignoring interactive_mode arg

- Cargo.lock
- Cargo.toml
- mistralrs-core/Cargo.toml
Refs https://github.com/EricLBuehler/candle/pull/58.
> Use cudarc fork to fix CUDA build on Windows

- mistralrs-core/src/models/phi3.rs
- mistralrs-core/src/vision_models/phi3/mod.rs
> Fix metal paged attn phi3

- mistralrs-bench/src/main.rs
> Improve pagedattn support in mistralrs bench

- mistralrs-quant/src/fp8/mod.rs
- mistralrs-quant/src/lib.rs
> Support loading blockwise quantized fp8

- mistralrs-core/src/pipeline/sampling.rs
- mistralrs-server/src/chat_completion.rs
- mistralrs-server/src/completions.rs
- mistralrs-server/src/interactive_mode.rs
Reduce keep alive duration and remove rate limit.
> Improve streaming UX

- Cargo.lock
> Use cudarc 0.13.5

- Cargo.lock
- Cargo.toml
- mistralrs-core/Cargo.toml
> Always pass _USE_MATH_DEFINES for CUDA

- Cargo.lock
- Cargo.toml
- mistralrs-core/Cargo.toml
- mistralrs-core/src/attention.rs
- mistralrs-core/src/pipeline/isq.rs
- mistralrs-quant/src/bitsandbytes/mod.rs
- mistralrs-quant/src/blockwise_fp8/mod.rs
- mistralrs-quant/src/distributed/layers.rs
- mistralrs-quant/src/dummy/mod.rs
- mistralrs-quant/src/fp8/mod.rs
- mistralrs-quant/src/gguf/mod.rs
- mistralrs-quant/src/gptq/gptq_cpu.rs
- mistralrs-quant/src/gptq/gptq_cuda.rs
- mistralrs-quant/src/hqq/mod.rs
- mistralrs-quant/src/lib.rs
- mistralrs-quant/src/unquantized/mod.rs
- mistralrs-quant/src/utils/isq.rs
https://github.com/ml-explore/mlx/pull/1924
Should provide a nice performance boost/smaller memory usage during prompts.
> Metal SDPA with masking

- mistralrs-core/src/attention.rs
> Fix nccl blocking case

- mistralrs-core/src/pipeline/normal.rs
> Use default stream for flash attn

- mistralrs-quant/src/afq/mod.rs
- mistralrs-quant/src/afq/ops.rs
- mistralrs-quant/src/gguf/mod.rs
- mistralrs-quant/src/lib.rs
- mistralrs-quant/src/metal_kernels/mod.rs
- mistralrs-quant/src/unquantized/mod.rs
> Gather MM ops in mistralrs-quant

- mistralrs-core/src/engine/mod.rs
- mistralrs-core/src/lib.rs
- mistralrs-core/src/models/quantized_llama.rs
- mistralrs-core/src/models/quantized_phi2.rs
- mistralrs-core/src/models/quantized_qwen.rs
- mistralrs-core/src/models/quantized_qwen3.rs
- mistralrs-core/src/pipeline/loaders/auto_device_map.rs
- mistralrs-core/src/pipeline/macros.rs
- mistralrs-core/src/xlora_models/quantized_llama.rs
- mistralrs-quant/src/cublaslt/mod.rs
- mistralrs-quant/src/gptq/gptq_cuda.rs
- mistralrs-quant/src/lib.rs
- mistralrs-quant/src/lora/mod.rs
Each engine runs in its own thread.
> Add thread_local! for engine-specific const/static

- mistralrs-core/src/sequence.rs
> Fix sequence length check

- Cargo.lock
- Cargo.toml
> update candle version

- mistralrs/src/text_model.rs
- mistralrs/src/vision_model.rs
Refs: https://github.com/EricLBuehler/mistral.rs/issues/1544#issuecomment-3079590955
> Improved Rust UQFF api

- Cargo.lock
- Cargo.toml
> Fix metal regression

- mistralrs-mcp/src/lib.rs
> Fix invalid HTML warning

- .github/ISSUE_TEMPLATE/build_failure.md
- .typos.toml
- ignore only complete identifiers
- ignore Rust names only in Rust files
- check dotfiles!
> Make typos configuration stricter

- mistralrs-core/src/utils/debug.rs
https://github.com/EricLBuehler/mistral.rs/issues/1587
> fix: use try_init when initialize tracing

- README.md
This small PR fixes the MCP server guide source in `README.md`.
> Update MCP server guide source
