mistralrs-core/src/pipeline/mod.rs
mistralrs-core/src/utils/tokens.rs
mistralrs-server/src/main.rs

This is useful for models which do not require authentication and when the HF token does not need to be provided.

Add support for 'none' token source

---

examples/http.md
mistralrs-core/src/engine/mod.rs
mistralrs-core/src/request.rs
mistralrs-pyo3/Cargo.toml
mistralrs-pyo3/mistralrs.pyi
mistralrs-pyo3/src/lib.rs
mistralrs-server/Cargo.toml
mistralrs-server/src/main.rs
mistralrs-server/src/openai.rs

Updates:
- `http.md` docs
- `mistralrs.pyi` type hints
Changes:
- `ChatCompletionReuqest::new` parsing/downcasting
- `ChatCompletionRequest` handles the string
- `Engine` handles not running the chat template if the prompt is already provided.

Allow input prompt message to be a String prompt

---

mistralrs-core/src/engine/mod.rs
mistralrs-server/src/main.rs

Closes https://github.com/EricLBuehler/mistral.rs/issues/97
```
curl -v http://localhost:1234/v1/chat/completions \
-H "Content-Type: application/json" \
-H "Authorization: Bearer EMPTY" \
-d '{
"model": "mistral",
"stop": "\n\n\n",
"temperature": 0,
"top_p": 0.1,
"frequency_penalty": 1.0,
"max_tokens": 256,
"messages": [
{
"role": "user",
"content": "Write a story about Rust error handling."
}
]
}'
*   Trying 127.0.0.1:1234...
* Connected to localhost (127.0.0.1) port 1234 (#0)
> POST /v1/chat/completions HTTP/1.1
> Host: localhost:1234
> User-Agent: curl/7.81.0
> Accept: */*
> Content-Type: application/json
> Authorization: Bearer EMPTY
> Content-Length: 216
> 
* Mark bundle as not supporting multiuse
< HTTP/1.1 500 Internal Server Error
< content-type: application/json
< …
```

Resolve "Status code of HTTP error messages is not 4xx or 5xx"

---

examples/server/chat.py
mistralrs-core/src/engine/mod.rs
mistralrs-core/src/pipeline/gemma.rs
mistralrs-core/src/pipeline/llama.rs
mistralrs-core/src/pipeline/mistral.rs
mistralrs-core/src/pipeline/mixtral.rs
mistralrs-core/src/pipeline/mod.rs
mistralrs-core/src/pipeline/phi2.rs
mistralrs-core/src/response.rs
mistralrs-core/src/sequence.rs
mistralrs-core/src/utils/mod.rs
mistralrs-pyo3/src/lib.rs
mistralrs-server/src/main.rs

I was playing around with the codebase, adding a few dbg! around and seeing what goes on under the hood.
While doing so I stumbled upon an Out of Memory error. I was using a very long prompt, and it won't fit my GPU indeed.
When this happened, the server no longer worked, the process was still alive and GPU memory had not been freed.
This behavior can be simulated with panicking anywhere in the forward function of the pipeline: https://github.com/EricLBuehler/mistral.rs/blob/master/mistralrs-core/src/pipeline/mistral.rs#L371
I changed the Pipeline trait to return errors on the forward pass instead of panicking. I handled the errors by setting all sequence states to error, deleting the GPU cache and sending an error message to the receiver.
This makes the server continue to work and frees …

Handle errors in forward pass, delete cache and cancel all sequences (Survive OOM)

---

examples/server/stream_completion_bench.py
mistralrs-core/src/engine/mod.rs
mistralrs-core/src/sequence.rs

It seems Axum/OpenAI libraries add ~300ms of overhead on opening/closing the stream.
I can always get this 300ms diff no matter the prompt length.
Using 400 tokens like in the .py file I'm sending I get 96% efficiency, close to Ollama's 97%.
It doesn't look like there's much to improve here.
Closes #99

Optimize streaming

---

mistralrs-core/src/engine/mod.rs
mistralrs-core/src/sequence.rs

Use `completion_bytes` if streaming or in regular mode.
Avoid re-decoding tokens when finishing requests in regular mode.
Removes unsafe and 1 allocation from the streaming code.
Avoid searching for the stop string, store position in reason.

Optimize completion strings

---

mistralrs-core/src/aici/recognizer.rs
mistralrs-core/src/aici/toktree.rs
mistralrs-core/src/engine/mod.rs
mistralrs-core/src/models/gemma.rs
mistralrs-core/src/models/llama.rs
mistralrs-core/src/models/mistral.rs
mistralrs-core/src/models/mixtral.rs
mistralrs-core/src/models/phi2.rs
mistralrs-core/src/models/quantized_llama.rs
mistralrs-core/src/pipeline/gemma.rs
mistralrs-core/src/pipeline/llama.rs
mistralrs-core/src/pipeline/mistral.rs
mistralrs-core/src/pipeline/mixtral.rs
mistralrs-core/src/pipeline/mod.rs
mistralrs-core/src/pipeline/phi2.rs
mistralrs-core/src/scheduler.rs
mistralrs-core/src/sequence.rs
mistralrs-core/src/xlora_models/gemma.rs
mistralrs-core/src/xlora_models/llama.rs
mistralrs-core/src/xlora_models/mistral.rs
mistralrs-core/src/xlora_models/mixtral.rs
mistralrs-core/src/xlora_models/phi2.rs
mistralrs-core/src/xlora_models/quantized_llama.rs

- Fixes Phi2 LoRA
- Allows all prompt seqs to run at the same time, all the time

Remove need for catchup KV cache scheduling

---

mistralrs-server/src/interactive_mode.rs

Due to the stream rate limit there was a chance we'd not print the latest 2 tokens of the message.

Fix interactive mode stripping end of message

---

Cargo.toml
mistralrs-core/Cargo.toml
mistralrs-core/src/engine/mod.rs
mistralrs-core/src/prefix_cacher.rs
mistralrs-core/src/sequence.rs
mistralrs-core/src/utils/mod.rs

Refs #126.
This changes:
- Searching strategy:
- Caching strategy:

Rework the prefix cacher

---

mistralrs-core/src/engine/mod.rs
mistralrs-core/src/pipeline/mod.rs
mistralrs-core/src/sampler.rs

Makes sampling fully async, removing synchronizations.
Generation goes from 54t/s to 59t/s using `./target/profiling/mistralrs-server --prompt "Tell me 3 jokes." mistral-gguf`
Same generation speed as Llama.cpp :smile:

Sampling optimizations

---

mistralrs-core/src/engine/mod.rs
mistralrs-core/src/response.rs
mistralrs-core/src/sequence.rs
mistralrs-server/src/prompt_mode.rs

Sampling is done on the GPU, so it's not possible to measure this timing without GPU synchronization.
It is misleading and I think it can be removed.
The only way to measure sampling is through nvidia profiler.

Remove sampling metrics

---

mistralrs-core/src/engine/mod.rs
mistralrs-core/src/scheduler.rs

Receive multiple requests at once to parallelize inputs
If nothing is scheduled, wait for requests sleeping
Now 2 prompts can be batched, before this MR they wouldn't.
```
$ RUST_LOG=debug ./target/release/mistralrs-server --prompt "Tell me 3 jokes." --prompt-concurrency 2 mistral-gguf
...
2024-04-16T01:52:28.211352Z DEBUG mistralrs_core::engine: Prompt[15, 15] Completion[] - 230ms
2024-04-16T01:52:28.350200Z DEBUG mistralrs_core::engine: Prompt[] Completion[16, 16] - 138ms
....
```

Improvements to hot loop request receiving

---

mistralrs-core/src/engine/mod.rs

https://github.com/lucasavila00/mistral.rs/commit/0e833feb794a7bfab76df12c76d86c7ae317190d removed tracing filters and this place used tracing::debug
Notice that regardless, it is still locked by the `RUST_LOG=debug` env var.

Use tracing::info in hot loop debugging

---

mistralrs-core/src/engine/mod.rs

Once masked fill no longer sinchronizes (https://github.com/EricLBuehler/mistral.rs/pull/162) our measurements stopped being fair.
Ideally we merge this first, then we're able to properly compare https://github.com/EricLBuehler/mistral.rs/pull/162 with master

Measure prompt time after sampling

---

mistralrs-core/src/models/quantized_llama.rs

Closes #161 
This MR:
```
Prompt T/s = 70.70707
Completion T/s = 61.244022
```
Master:
```
Prompt T/s = 59.82906
Completion T/s = 61.538464
```

Optimize quantized masked fill

---

mistralrs-core/Cargo.toml
mistralrs-core/src/prefix_cacher.rs

This uses a Radix Trie: https://docs.rs/radix_trie/latest/radix_trie/index.html according to [this](https://lmsys.org/blog/2024-01-17-sglang/) post. It refactors the prefix cacher extensively and simplifies it in the process. Hopefully, this fixes #179.

Refactor the PrefixCacher

---

mistralrs-core/src/engine/mod.rs
mistralrs-core/src/sequence.rs

Fixes #213
I don't know if this is the correct way to fix this but we should probably have some mechanism, that cancels and cleans up a sequence if we can't send the results anywhere.

Mark sequence as `Canceled` if the `responder` isn't there

---

mistralrs-core/src/engine/mod.rs

```
./target/profiling/mistralrs-bench -p 0 -g 64 -r 1 -c 8  gguf -t mistralai/Mistral-7B-Instruct-v0.1 -m TheBloke/Mistral-7B-Instruct-v0.1-GGUF -f mistral-7b-instruct-v0.1.Q4_K_M.gguf
```
Master
This PR
Saves the highlighted 2ms when copying the 63th token's cache in.

Skip cloning cache in redundantly

---

mistralrs-core/src/engine/mod.rs

If running in interactive mode it was calculating the time it takes to type the message as time of the first token

Fix debug log timing of first token

---

mistralrs-core/src/engine/mod.rs
mistralrs-core/src/sampler.rs

I found it while testing https://github.com/EricLBuehler/mistral.rs/pull/236

Fix quantized example

---

mistralrs-core/src/layers.rs
mistralrs-core/src/models/mistral.rs
mistralrs-core/src/models/mixtral.rs
mistralrs-core/src/models/phi3.rs
mistralrs-core/src/pipeline/loaders.rs
mistralrs-core/src/xlora_models/mistral.rs
mistralrs-core/src/xlora_models/mixtral.rs
mistralrs-core/src/xlora_models/phi3.rs

2 major lessons:
- Need to slice the kv cache for sliding window
- RoPE freqs cannot be cast into low precision quickly, only after the cos/sin application: https://github.com/huggingface/transformers/pull/29285

Sliding window for phi3

---

mistralrs-core/src/layers.rs
mistralrs-core/src/models/gemma.rs
mistralrs-core/src/models/llama.rs
mistralrs-core/src/models/mistral.rs
mistralrs-core/src/models/mixtral.rs
mistralrs-core/src/models/phi2.rs
mistralrs-core/src/models/phi3.rs
mistralrs-core/src/models/qwen2.rs
mistralrs-core/src/pipeline/ggml.rs
mistralrs-core/src/pipeline/gguf.rs
mistralrs-core/src/pipeline/mod.rs
mistralrs-core/src/pipeline/normal.rs
mistralrs-core/src/xlora_models/gemma.rs
mistralrs-core/src/xlora_models/llama.rs
mistralrs-core/src/xlora_models/mistral.rs
mistralrs-core/src/xlora_models/mixtral.rs
mistralrs-core/src/xlora_models/mod.rs
mistralrs-core/src/xlora_models/phi2.rs
mistralrs-core/src/xlora_models/phi3.rs
mistralrs-core/src/xlora_models/quantized_llama.rs

Before, we used the start offset. This is not correct. Now, we use position ids based on the context length and past KV length.

Fix Phi3 128k finally: use position ids to switch between short/long scaling

---

mistralrs-bench/Cargo.toml
mistralrs-bench/src/main.rs
mistralrs-core/src/engine/mod.rs
mistralrs-core/src/lib.rs
mistralrs-core/src/request.rs
mistralrs-core/src/sequence.rs
mistralrs-core/src/utils/mod.rs
mistralrs-pyo3/Cargo.toml
mistralrs-pyo3/src/lib.rs
mistralrs-pyo3/src/stream.rs
mistralrs-server/src/chat_completion.rs
mistralrs-server/src/completions.rs
mistralrs-server/src/interactive_mode.rs
mistralrs-server/src/main.rs
mistralrs/Cargo.toml
mistralrs/examples/grammar/main.rs
mistralrs/examples/isq/main.rs
mistralrs/examples/quantized/main.rs
mistralrs/examples/simple/main.rs

Closes https://github.com/EricLBuehler/mistral.rs/issues/235

Async channels

---

mistralrs-server/src/interactive_mode.rs

Resolves the issue reported in #266 by allowing piping data into interactive mode.
New behavior: if the input received by read_line is empty (there was an EOF) then interactive mode is stopped.

Support EOF in interactive mode

---

mistralrs-core/src/layers.rs

Fix concat in PhiRotaryEmbedding

---

mistralrs-bench/src/main.rs

Warmup pass for mistralrs-bench

---

mistralrs-core/src/layers.rs
mistralrs-core/src/models/mod.rs
mistralrs-core/src/models/quantized_phi3.rs
mistralrs-core/src/pipeline/gguf.rs

Add the quantized phi3 model

---

mistralrs-core/src/scheduler.rs
mistralrs-core/src/sequence.rs

Introduces sequence priority, a function of the number of scheduling passes since it was run, and the length. This prepares for #262.
We multiply to ensure that if the sequence is long, but it was just scheduled, then newer sequences get a chance too.
Formula:
$Priority = \log_2{Length} + Urgency$
Where the urgency is the number of scheduler passes since the sequence was scheduled.

More intelligent scheduler

---

mistralrs-core/src/pipeline/mod.rs

Since the `k-quants` can be quite strict with their block size of `256` we can simply fallback to a simillar "normal" quantization level and if that doesnt work we should just skip the tensor and print a warning.

Add some "senseful" fallbacks for `isq`

---

mistralrs-core/src/pipeline/speculative.rs

Doesn't use Algorithm 1 from the paper, but it works and is 1.3x the speed.

Make speculative decoding faster without anything fancy

---

Dockerfile
Dockerfile-cuda-all
mistralrs-core/Cargo.toml
mistralrs-core/src/pipeline/loaders.rs
mistralrs-core/src/response.rs
mistralrs-core/src/sampler.rs
mistralrs-pyo3/Cargo.toml
mistralrs-pyo3/Cargo_template.toml

Puts `pyo3` behind the `pyo3_macros` feature flag, which is set per default in the `mistralrs-pyo3` create. 
This allows us to compile the benchmark/server without any python depencies via: 
```
cargo build --release --workspace --exclude mistralrs-pyo3
```

Make `pyo3` an optional dependency in `mistralrs-core`

---

mistralrs-core/src/models/quantized_llama.rs

Don't force QLlama to have >2 input dims  @Jeadie

---

mistralrs-bench/src/main.rs
mistralrs-core/src/device_map.rs
mistralrs-core/src/pipeline/ggml.rs
mistralrs-core/src/pipeline/gguf.rs
mistralrs-core/src/pipeline/normal.rs
mistralrs-server/src/main.rs

Fixes and verbosity improvements for device mapping

---

mistralrs-core/src/pipeline/mod.rs

This was originally carried out in https://github.com/EricLBuehler/mistral.rs/commit/07ea5b3039ab7a92a4b9e38967bc5c1e1b8df026 as part of https://github.com/EricLBuehler/mistral.rs/pull/308
When I was troubleshooting https://github.com/EricLBuehler/mistral.rs/issues/326#issuecomment-2118647910 I came across this comment but wasn't quite sure what it was referencing. Later I spotted the mentioned commit when looking at recent history and realized this line was accidentally missed 😅

chore: `SimpleModelPaths` should be renamed to `LocalModelPaths`

---

mistralrs-core/src/pipeline/macros.rs
mistralrs-core/src/pipeline/mod.rs
mistralrs-core/src/utils/tokens.rs

Presently when a token is not considered valid via this utility method, it is treated as an empty string `Some("")` to hand over to the `hf-hub` crate API, but it should have instead been provided as `None`?
From the `hf-hub` crate, you can see that this would [avoid adding a blank authorization HTTP header](https://github.com/huggingface/hf-hub/blob/9d6502f5bc2e69061c132f523c76a76dad470477/src/api/sync.rs#L143-L157)
```rs
/// Sets the token to be used in the API
pub fn with_token(mut self, token: Option<String>) -> Self {
self.token = token;
self
}
fn build_headers(&self) -> HeaderMap {
let mut headers = HeaderMap::new();
let user_agent = format!("unkown/None; {NAME}/{VERSION}; rust/unknown");
headers.insert(USER_AGENT, user_agent);
if let Some(token) = &self.token { …
```

chore: Simplify `utils/token.rs:get_token()`

---

mistralrs-core/Cargo.toml
mistralrs-core/src/pipeline/gguf.rs

Minor improvement to consider?
- Minimizes some noise when assigning `arch` from metadata (_that is read via the `candle` crate_).
- Custom `FromStr` can be replaced by `strum` derive, making it DRY, adding a new variant no longer needs to update the string mapping.
- Both concerns now handled in smaller `from_value()` method.

chore: Use `strum` to simplify `GGUFArchitecture` maintenance

---

mistralrs-bench/src/main.rs
mistralrs-core/Cargo.toml
mistralrs-core/src/pipeline/mod.rs
mistralrs-core/src/pipeline/normal.rs
mistralrs-server/src/main.rs

This is something to consider, but would be a bit awkward without replacing `ModelKind` as a breaking change.
It was something I explored after https://github.com/EricLBuehler/mistral.rs/pull/334 and depends on it for `strum`, likewise I've not added the derive-more crate here either. Going forward with such a change for this type would be rather large, but can be done if deemed worthwhile.
I noticed quite a bit of logic to support the different kinds is mostly repeated with very little if any differences. Meanwhile some logic looks like it's already falling out of sync, thus reducing the noise throughout the codebase may help focus on minimizing that concern?
---
I'm not sure if `Lora` quantized kinds were intentionally excluded here, could simply be a call to `kind.is_quantized()`?: …

refactor: `ModelKind` with `strum` + `derive_more`

---

mistralrs/examples/grammar/main.rs
mistralrs/examples/isq/main.rs
mistralrs/examples/lora/main.rs
mistralrs/examples/lora_activation/main.rs
mistralrs/examples/quantized/main.rs
mistralrs/examples/simple/main.rs
mistralrs/examples/xlora/main.rs
mistralrs/src/lib.rs

- All public items from `mistralrs_core`
- Expose items from `candle_core` to avoid end users needing to add the candle dependancy: `GgmlDType`, `Device`, `DType`, `Result`.

Expose some APIs on the Rust side

---

mistralrs-core/src/aici/recognizer.rs
mistralrs-core/src/aici/rx.rs
mistralrs-core/src/engine/mod.rs

I found that certain Regex constraints can panic and bring down the whole engine. For example, take this constraint: `constraint: Constraint::Regex("[a-z]*".to_string()).` We get:
```
thread '<unnamed>' panicked at mistralrs-core/src/aici/rx.rs:35:14:
dfa has no universal start state; make sure it doesn't match empty string
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread 'main' panicked at mistralrs/examples/quantized/main.rs:57:39:
called `Option::unwrap()` on a `None` value
fish: Job 1, 'cargo run --example quantized -…' terminated by signal SIGSEGV (Address boundary error)
```
Not sure if this is a solid fix, but I just pushed the error up into StackRecognizer creation. Now, the engine can handle this initialization error and return a Validation …

Propogating Regex init error

---

mistralrs-core/Cargo.toml
mistralrs-core/src/utils/mod.rs
mistralrs-core/src/utils/progress.rs
mistralrs-core/src/utils/varbuilder_utils.rs

The bulk of this file has 4 variants to accomodate common vs x-lora + optionally `tqdm` progress bar via `silent` bool condition.
Refactored to use iterators and a trait for handling divergence with x-lora. Much more easier to maintain and grok! 😎 
---
Additionally the approach for handling opt-in/out on progress when using `iter.tqdm()` has been extracted out to it's own utility (_thanks to the rust community for assisting with that as I was a bit stumped_ 😅 ).
Presently models in `mistralrs-core` use `tqdm()` but there is no opt-out like here. If you want that, perhaps the CLI could set a global static early on for the setting, no parameter would be needed to tossed through layers of functions then?
---
There was discussion to better name the parameters here, to clear up some ambiguity …

refactor: DRY `varbuilder_utils.rs`

---

mistralrs-core/src/models/gemma.rs
mistralrs-core/src/models/llama.rs
mistralrs-core/src/models/mistral.rs
mistralrs-core/src/models/mixtral.rs
mistralrs-core/src/models/phi2.rs
mistralrs-core/src/models/phi3.rs
mistralrs-core/src/models/qwen2.rs
mistralrs-core/src/pipeline/macros.rs
mistralrs-core/src/pipeline/mod.rs
mistralrs-core/src/pipeline/normal_loaders.rs
mistralrs-core/src/xlora_models/gemma.rs
mistralrs-core/src/xlora_models/llama.rs
mistralrs-core/src/xlora_models/mistral.rs
mistralrs-core/src/xlora_models/mixtral.rs
mistralrs-core/src/xlora_models/phi2.rs
mistralrs-core/src/xlora_models/phi3.rs

Prepares for automatic detection of GPU VRAM and therefore calculating maximum number of device layers. Refs #377.

Organize normal loading metadata

---

mistralrs-core/src/lib.rs
mistralrs-core/src/pipeline/chat_template.rs
mistralrs-core/src/pipeline/mod.rs
mistralrs-core/src/pipeline/speculative.rs
mistralrs-server/src/main.rs

I'm not familiar with the syntax, I've assumed markdown.
This PR should address the issues the action keeps annotating about unrelated to actual PR changes.

docs: Resolve CI lints on docs

---

README.md
mistralrs-bench/src/main.rs
mistralrs-core/src/lib.rs
mistralrs-core/src/model_loader.rs
mistralrs-core/src/model_selected.rs
mistralrs-core/src/pipeline/ggml.rs
mistralrs-core/src/pipeline/gguf.rs
mistralrs-core/src/pipeline/macros.rs
mistralrs-core/src/pipeline/mod.rs
mistralrs-core/src/pipeline/normal.rs
mistralrs-core/src/pipeline/speculative.rs
mistralrs-core/src/pipeline/vision.rs
mistralrs-core/src/toml_selector.rs
mistralrs-core/src/utils/mod.rs
mistralrs-core/src/utils/normal.rs
mistralrs-pyo3/src/lib.rs
mistralrs-pyo3/src/which.rs
mistralrs-server/src/main.rs
mistralrs/examples/gguf_locally/main.rs
mistralrs/examples/grammar/main.rs
mistralrs/examples/isq/main.rs
mistralrs/examples/lora/main.rs
mistralrs/examples/lora_activation/main.rs
mistralrs/examples/phi3v/main.rs
mistralrs/examples/quantized/main.rs
mistralrs/examples/simple/main.rs
mistralrs/examples/xlora/main.rs

This PR exposes an API to either specify a concrete dtype during loading, or automatically determine the correct dtype.

Expose API to specify dtype during loading

---

mistralrs-core/Cargo.toml
mistralrs-core/src/pipeline/chat_template.rs

This switches to MiniJinja's new pycompat code to avoid the manual string manipulation.
See https://docs.rs/minijinja-contrib/latest/minijinja_contrib/pycompat/fn.unknown_method_callback.html

Switch to minijinja's pycompat mode

---

README.md
docs/ISQ.md
mistralrs-core/src/pipeline/isq.rs

Currently when loading with ISQ, there is a spike in GPU memory usage. This is because tensors are copied to the GPU asynchronously and quantized. By forcing a GPU <> CPU synchronization, we can ensure that there is no overlap of operations and that copies are completed, meaning that the spike should be reduced.

Lower memory spike when loading with ISQ on CUDA

---

mistralrs-core/build.rs

Support for the CUDA_NVCC_FLAGS flag. Refs #395.

NVCC flags support for mistralrs_core build

---

mistralrs-core/src/cuda/nonzero_bitwise.cu

Fix for bug in issue [https://github.com/EricLBuehler/mistral.rs/issues/395](https://github.com/EricLBuehler/mistral.rs/issues/395).
I didn't add any error message so feel free to add one. I think it's okay to let it bypass that code when it's zero (prevent divide by zero). I ran llama and there was no issues on my end.

Prevent divide by zero in cuda kernel

---

mistralrs-core/src/models/gemma.rs
mistralrs-core/src/models/llama.rs
mistralrs-core/src/models/mistral.rs
mistralrs-core/src/models/mixtral.rs
mistralrs-core/src/models/phi2.rs
mistralrs-core/src/models/phi3.rs
mistralrs-core/src/models/quantized_llama.rs
mistralrs-core/src/models/quantized_phi2.rs
mistralrs-core/src/models/quantized_phi3.rs
mistralrs-core/src/models/qwen2.rs
mistralrs-core/src/pipeline/cache_manager.rs
mistralrs-core/src/pipeline/ggml.rs
mistralrs-core/src/pipeline/gguf.rs
mistralrs-core/src/pipeline/mod.rs
mistralrs-core/src/pipeline/normal.rs
mistralrs-core/src/pipeline/speculative.rs
mistralrs-core/src/pipeline/vision.rs
mistralrs-core/src/utils/mod.rs
mistralrs-core/src/vision_models/idefics2.rs
mistralrs-core/src/vision_models/phi3.rs
mistralrs-core/src/xlora_models/gemma.rs
mistralrs-core/src/xlora_models/llama.rs
mistralrs-core/src/xlora_models/mistral.rs
mistralrs-core/src/xlora_models/mixtral.rs
mistralrs-core/src/xlora_models/mod.rs
mistralrs-core/src/xlora_models/phi2.rs
mistralrs-core/src/xlora_models/phi3.rs
mistralrs-core/src/xlora_models/quantized_llama.rs
mistralrs-core/src/xlora_models/quantized_phi3.rs

Remove some unnecessary `&mut`s

---

mistralrs-pyo3/mistralrs.pyi

Non-default was following default which caused the docs to be incorrectly generated.

Fix arg order for pdoc

---

Cargo.lock
Cargo.toml
README.md
docs/ISQ.md
mistralrs-core/Cargo.toml
mistralrs-core/src/device_map.rs
mistralrs-core/src/models/gemma.rs
mistralrs-core/src/models/gemma2.rs
mistralrs-core/src/pipeline/isq.rs
mistralrs-core/src/xlora_models/gemma.rs
mistralrs-pyo3/Cargo_template.toml

This will remove the necessity for the "ISQ_LOW_MEMORY" environment variable because it will enable quantization on the CPU.

Utilize new quantize_onto qtensor api

---

Cargo.lock
Cargo.toml

Refs NixOS/nixpkgs#319008, decreases MSRV to 1.75.0. Removes AVIF support but this is an OK cost.

Decrease MSRV to 1.75.0

---

mistralrs-core/src/layers.rs

Keep invfreq in f32. Refs #505.

Avoid f64 to f32 cast in phirope for dtype on metal

---

Cargo.lock
examples/python/anymoe_inference.py
examples/python/anymoe_lora.py
mistralrs-core/Cargo.toml
mistralrs-core/src/amoe/mod.rs
mistralrs-core/src/pipeline/amoe.rs
mistralrs-pyo3/mistralrs.pyi
mistralrs-pyo3/src/anymoe.rs
mistralrs-pyo3/src/lib.rs
mistralrs/examples/anymoe/main.rs
mistralrs/examples/anymoe_lora/main.rs
toml-selectors/anymoe.toml
toml-selectors/anymoe_lora.toml

Create an AnyMoE loss graph

---

mistralrs-core/src/pipeline/macros.rs

In the original logic of marcos.os, regardless of whether model_id is a valid ID on Hugging Face, a request to Hugging Face is made, and if the request fails, it then attempts to load from the local environment. However, if the network environment cannot connect to Hugging Face normally, this step becomes very slow, with each API call attempt taking tens of seconds. Therefore, I have added a workaround here: first, it checks whether model_id is an absolute path. If it is, it directly loads from the local environment. This simple modification directly reduces the time spent on load_model_from_hf from 1 to 2 minutes to just a few microseconds 🤣
Edit: Now I change to check if model_id exists as a local path

Add judgment for whether model_id is a local path to speed up local model loading

---

.github/workflows/release.yml
Cargo.toml
mistralrs-bench/Cargo.toml

Fixes: https://github.com/EricLBuehler/mistral.rs/issues/263
As of now, musl and windows based build are disabled because they were [breaking](https://github.com/kranurag7/mistral.rs/actions/runs/9666023904), I can take a look at fixing those later. 
I created a release on my fork here: https://github.com/kranurag7/mistral.rs/releases/tag/v0.1.24

release using cargo-dist

---

mistralrs-core/src/models/gemma2.rs
mistralrs-core/src/xlora_models/gemma2.rs

At the time of porting, we used the Transformers implmentation which had the SWA order flipped w.r.t the [Google implementation](https://github.com/google/gemma_pytorch/blob/1814f8d0a6ba93b875c46a64e6ad1873df448eef/gemma/config.py#L118).
Refs huggingface/transformers#31775.

Fix SWA order (flip it) for Gemma 2

---

mistralrs-core/src/models/quantized_llama.rs
mistralrs-core/src/paged_attention/layers/mod.rs
mistralrs-core/src/paged_attention/mod.rs
mistralrs-core/src/pipeline/gguf.rs
mistralrs-core/src/pipeline/paths.rs
mistralrs-server/src/main.rs

This PR fix the generation issue for the newly introduced paged-attention approach, I have only tested the quantized_llama model with command line:
```
cargo run --release --features cuda -- --port 2000 --chat-template ./chat_templates/llama2.json -i gguf -t /home/llama2_7b/ -m TheBloke/Llama-2-7B-Chat-GGUF -f /home/llama-2-7b-chat.Q4_K_M.gguf
```
I also changed the `-f` parameter to accept local gguf model file.

Fix generation issue for the paged-attention approach.

---

mistralrs-core/src/pipeline/paths.rs

Fix handling of things like `consolidated.safetensors` in Mistral v0.3

Add matching for valid model weight names

---

mistralrs-core/build.rs

Handles `mistralcuda.lib` on Windows VS `libmistralcuda.a`.

Update cuda kernels build.rs on windows

---

mistralrs-core/src/models/mistral.rs
mistralrs-core/src/pipeline/normal_loaders.rs
mistralrs-core/src/vision_models/idefics2.rs
mistralrs-core/src/vision_models/llava/config.rs
mistralrs-core/src/xlora_models/mistral.rs

mistralai/Mistral-Nemo-Instruct-2407

Add support for mistral nemo

---

mistralrs-server/src/main.rs

Fix server cross-origin errors
1. Axum Router is a stack model.
2. To enhance cross-domain compatibility, the LLM client will provide an `AUTHORIZATION` header in its requests.

Fix server cross-origin errors

---

Cargo.lock
mistralrs-bench/Cargo.toml
mistralrs-bench/src/main.rs
mistralrs-core/src/dummy_paged_attention/mod.rs
mistralrs-core/src/lib.rs
mistralrs-core/src/paged_attention/mod.rs
mistralrs-paged-attn/build.rs
mistralrs-paged-attn/src/backend/paged_attention.rs
mistralrs-paged-attn/src/lib.rs
mistralrs-pyo3/mistralrs.pyi
mistralrs-pyo3/src/lib.rs
mistralrs-server/src/main.rs
mistralrs/examples/paged_attn/main.rs

Allow setting PagedAttention KV cache allocation from context size

---

mistralrs-pyo3/src/lib.rs

Fixed the function return type to be a `Device` on `get_device()`.
-----
**Background**
With `cargo build --release --features metal` I was seeing this build error:
```
error[E0107]: enum takes 2 generic arguments but 1 generic argument was supplied
--> mistralrs-pyo3/src/lib.rs:50:20
|
50  | fn get_device() -> Result<Device> {
|                    ^^^^^^ ------ supplied 1 generic argument
|                    |
|                    expected 2 generic arguments
|
note: enum defined here, with 2 generic parameters: `T`, `E`
--> /Users/kylekelley/.rustup/toolchains/nightly-aarch64-apple-darwin/lib/rustlib/src/rust/library/core/src/result.rs:527:10
|
527 | pub enum Result<T, E> {
|          ^^^^^^ -  -
help: add missing generic argument
|
50  | fn get_device() -> Result<Device, E> {
| …
```

fix build on metal by returning Device

---

mistralrs-core/src/sampler.rs

Review of #637. Intended to be read commit-by-commit.

Review: "Implement DRY penalty"

---

mistralrs-core/src/pipeline/ggml.rs
mistralrs-core/src/pipeline/gguf.rs
mistralrs-core/src/pipeline/normal.rs
mistralrs-core/src/pipeline/vision.rs

Device mapping is incompatible with PagedAttention because the KV cache needs to all be on 1 GPU.

Fix device map check for paged attn

---

mistralrs-core/src/utils/normal.rs

Fixes https://github.com/EricLBuehler/mistral.rs/issues/630#issuecomment-2288551704

Add missing error case in automatic dtype selection feature

---

mistralrs-core/src/utils/normal.rs

Fixes for auto dtype selection with RUST_BACKTRACE=1

---

mistralrs-core/src/gguf/chat_template.rs
mistralrs-core/src/gguf/content.rs
mistralrs-core/src/gguf/gguf_tokenizer.rs
mistralrs-core/src/gguf/mod.rs
mistralrs-core/src/layers.rs
mistralrs-core/src/lib.rs
mistralrs-core/src/model_loader.rs
mistralrs-core/src/model_selected.rs
mistralrs-core/src/models/quantized_llama.rs
mistralrs-core/src/models/quantized_phi2.rs
mistralrs-core/src/models/quantized_phi3.rs
mistralrs-core/src/models/quantized_starcoder2.rs
mistralrs-core/src/pipeline/gguf.rs
mistralrs-core/src/pipeline/macros.rs
mistralrs-core/src/pipeline/mod.rs
mistralrs-core/src/toml_selector.rs
mistralrs-core/src/utils/model_config.rs
mistralrs-core/src/xlora_models/quantized_llama.rs
mistralrs-core/src/xlora_models/quantized_phi3.rs
mistralrs-pyo3/API.md
mistralrs-pyo3/mistralrs.pyi
mistralrs-pyo3/src/lib.rs
mistralrs-pyo3/src/which.rs
mistralrs/examples/gguf_locally/main.rs
mistralrs/examples/quantized/main.rs

Add support multiple GGUF files

---

Cargo.lock
Cargo.toml
mistralrs-core/Cargo.toml
mistralrs-core/src/device_map.rs
mistralrs-core/src/engine/mod.rs
mistralrs-core/src/pipeline/amoe.rs
mistralrs-core/src/pipeline/isq.rs
mistralrs-core/src/pipeline/mod.rs
mistralrs-core/src/pipeline/normal.rs
mistralrs-core/src/pipeline/processing.rs
mistralrs-core/src/pipeline/sampling.rs
mistralrs-core/src/pipeline/speculative.rs
mistralrs-core/src/pipeline/vision.rs
mistralrs-core/src/vision_models/idefics2_input_processor.rs
mistralrs-pyo3/Cargo_template.toml

Refs huggingface/candle#2467, EricLBuehler/candle#21.

Use nicer Candle Error APIs 

---

mistralrs-core/src/models/gemma.rs
mistralrs-core/src/models/gemma2.rs
mistralrs-core/src/models/llama.rs
mistralrs-core/src/models/mistral.rs
mistralrs-core/src/models/mixtral.rs
mistralrs-core/src/models/phi2.rs
mistralrs-core/src/models/phi3.rs
mistralrs-core/src/models/phi3_5_moe.rs
mistralrs-core/src/models/quantized_llama.rs
mistralrs-core/src/models/quantized_starcoder2.rs
mistralrs-core/src/models/qwen2.rs
mistralrs-core/src/models/starcoder2.rs
mistralrs-core/src/vision_models/phi3.rs
mistralrs-core/src/xlora_models/gemma.rs
mistralrs-core/src/xlora_models/gemma2.rs
mistralrs-core/src/xlora_models/llama.rs
mistralrs-core/src/xlora_models/mistral.rs
mistralrs-core/src/xlora_models/mixtral.rs
mistralrs-core/src/xlora_models/phi2.rs
mistralrs-core/src/xlora_models/phi3.rs
mistralrs-core/src/xlora_models/quantized_llama.rs
mistralrs-core/src/xlora_models/starcoder2.rs

Reduces memory consumption for Phi 3.5 mini, ISQ=Q4K from 4000MB to 2500MB.

Deduplicate RoPE caches

---

Cargo.lock
Cargo.toml
mistralrs-core/Cargo.toml
mistralrs-core/src/pipeline/isq.rs
mistralrs-pyo3/Cargo_template.toml

Metal: MLX
CUDA: PaddedData for quantized
@ChristianWeyer could you please test if this builds on Metal?

Update Metal, CUDA Candle impls and ISQ

---

.github/workflows/analysis.yaml
.github/workflows/build_cpu.yaml
.github/workflows/build_cuda_all.yaml
.github/workflows/ci.yml
.github/workflows/docs.yml
.github/workflows/release_python.yml

Minor house keeping for the CI. I don't think there are any breaking changes to account for, but I did notice that your `actions-rs` steps have archived their actions in Oct 2023 so you may need to migrate away from those at some point.

ci: Upgrade actions

---

mistralrs-core/src/pipeline/loaders/vision_loaders.rs

saw this in [cpu-0.3.1](ghcr.io/ericlbuehler/mistral.rs:cpu-sha-1caf83a@sha256:b7acce1fa5cbc8595f5d973b7c6c643ff2d7bb678583d747c2ac1fc4f90950e6)

Typo in error of model architecture enum

---

Cargo.toml

Currently passing --help prints text without proper formatting. Adding the wrap_help feature to clap fixes this issue.

Adds wrap_help feature to clap

---

Cargo.lock
mistralrs-core/src/pipeline/isq.rs

It seems like the Metal device can only be created once per ordinal. It needs investigation, but this PR is a fix.

Avoid duplicate Metal command buffer encodings during ISQ

---

mistralrs-quant/build.rs

Hello,
I'm encountering a build error from the latest `master` (`7a67ddaf`) on Windows 11.
It appears to be due to `nvidia-smi`'s line endings being CR LF. This fix just trims whitespace from the compute cap, allowing it to be parsed correctly.
My build environment, for reference:
```
rustc 1.82.0 (f6e511eec 2024-10-15)
Microsoft (R) C/C++ Optimizing Compiler Version 19.41.34123 for x64
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2024 NVIDIA Corporation
Built on Thu_Mar_28_02:30:10_Pacific_Daylight_Time_2024
Cuda compilation tools, release 12.4, V12.4.131
Build cuda_12.4.r12.4/compiler.34097967_0
```

Trim whitespace (such as carriage returns) from nvidia-smi output.

---

mistralrs-core/src/lib.rs
mistralrs-core/src/request.rs

Fixed 'mspc' to 'mpsc' in rustdoc comments.

Fix typo in documentation

---

mistralrs-quant/src/hqq/hqq_cpu.rs
mistralrs-quant/src/utils/ops.rs

This confirms that `test_bitpack` is running solely on non-CPU hardware. To address this, we could implement a fix by ensuring contiguous data slices.

fix Half-Quadratic Quantization and Dequantization on CPU

---

mistralrs-core/src/vision_models/qwen2vl/inputs_processor.rs
mistralrs-vision/src/transforms.rs

Also, better error message. See #935.

Always cast image to rgb8 for qwenvl2

---

mistralrs-core/src/attention.rs
mistralrs-core/src/vision_models/mllama/vision.rs

\image https://www.nhmagazine.com/content/uploads/2019/05/mtwashingtonFranconia-2-19-18-108-Edit-Edit.jpg What is this?
After PR:
+ ~8GB
Before PR:
+ ~30GB
Improved usage by 22GB!

Improve memory efficency of vllama

---

Cargo.toml

The `is_none_or` function was introduced in 1.82. 
BTW, maybe we need 1.83?

set minimum rustc version to 1.82

---

mistralrs/examples/gguf_locally/main.rs

The `gguf_locally` example was failing due to a mismatch between the chat template (chat_templates/mistral.json) and the example code. The chat template only supports 'user' and 'assistant' roles, but the example code included a 'system' role message.
When running the example, I encountered the following error:
```
Error: invalid operation: Conversation roles must alternate user/assistant/user/assistant/... (in chat_template:1)
```
This PR removes the 'system' role message from the example code to allow it to run successfully.

Fix example gguf_locally to match chat template requirements

---

README.md

Remove outdated binaries mention, as they are unfortunately not published anymore.
See https://github.com/EricLBuehler/mistral.rs/issues/764

Remove outdated binaries mention in the readme

---

mistralrs-core/src/pipeline/ggml.rs
mistralrs-core/src/pipeline/gguf.rs
mistralrs-core/src/pipeline/normal.rs
mistralrs-core/src/pipeline/vision.rs

Currently, when the `bos_token_id` or `eos_token_id` field is missing from `generation_config.json`, the error message is "Error(`missing field `bos_token_id`", line: 4, column: 1)", which does not provide clear context about the source of the issue.
This change indicates the problem is in the `generation_config.json` file.

Improve error handling

---

mistralrs-core/src/prefix_cacher.rs

This check is already present in the `evict_to_cpu` function and was missing in `evict_all_to_cpu`.
Note: I'm not entirely sure if the comment is relevant here, I just copied it from the `evict_to_cpu` function - still getting familiar with the code

Add None check to prevent panic in evict_all_to_cpu in prefix_cacher.rs

---

mistralrs-core/src/pipeline/cache_manager.rs

Currently, in models like Phi3 and Mistral, with paged attention disabled, sliding window attention fails when the input sequence length exceeds the sliding window size, due to a "start > dim_len" error caused by the mask tensor being narrowed using its original length. 
An initial fix was updating the mask length after the first narrow operation, but this brings up another error where the mask's dimension was one higher than the corresponding dimension in the key and value tensors, leading to a shape mismatch in the `naive_sdpa` function.
The issue was resolved by removing the concatenation of the mask tensor, resulting in coherent outputs for non-flash attention, although flash attention remains non-functional. 
Any feedback or review of this change would be greatly appreciated!

Partial Fix for Sliding Window Attention

---

mistralrs-core/src/lib.rs
mistralrs-server/src/main.rs

Convenience flag to allow users to run the model purely on the CPU. If you have any feedback or would like to request changes, please let me know!

Add `--cpu` flag to `mistralrs-server`

---

Cargo.lock
mistralrs-core/src/lib.rs
mistralrs-core/src/models/quantized_phi3.rs
mistralrs-paged-attn/Cargo.toml
mistralrs-paged-attn/src/metal/backend/cache.rs
mistralrs-paged-attn/src/metal/backend/paged_attention.rs
mistralrs-paged-attn/src/metal/kernels/mod.rs

The metal kernels need to be loaded with load_source in each of the function callls in the current implementation because there is no global kernel cache, this PR fix the problem.

Fix bug for kernel cache & Phi3 inference

---

README.md
mistralrs-core/src/model_loader.rs
mistralrs-core/src/model_selected.rs
mistralrs-core/src/models/quantized_llama.rs
mistralrs-core/src/models/quantized_phi2.rs
mistralrs-core/src/models/quantized_phi3.rs
mistralrs-core/src/models/quantized_qwen2.rs
mistralrs-core/src/models/quantized_starcoder2.rs
mistralrs-core/src/pipeline/ggml.rs
mistralrs-core/src/pipeline/gguf.rs
mistralrs-core/src/pipeline/paths.rs
mistralrs-core/src/toml_selector.rs
mistralrs-core/src/utils/model_config.rs
mistralrs-core/src/xlora_models/quantized_llama.rs
mistralrs-core/src/xlora_models/quantized_phi3.rs
mistralrs-server/src/main.rs

The current approach for inference of GGUF/GGML models requires the input data type to be `F32` due to limitations in kernel implementations for quantized matmul, which necessitate an `F32` input and quantized weights. This limitation causes side effects, making attention mechanisms (including SDPA, paged attention, and flash attention) and the KV cache also to be `F32`.  
This PR addresses the issue by allowing the data type to be specified for GGUF/GGML models and casting the `F32` results of quantized matmuls to `BF16`. This casting applies to subsequent attention operations, rotary embeddings, and KV cache storage. As a result, KV cache usage is reduced by half, and inference performance is improved due to the use of `BF16` for matmuls and attentions.
On Apple Silicon (`Metal`), run …

Support BF16 kvcache, rope and attentions for inference of GGUF/GGML models

---

mistralrs-core/src/engine/mod.rs

We need a nice fix, this just disables the prefix cacher when prefix caching is enabled, setting the non-PA pre op to `Nothing` makes it work but breaks many other cases as reported in #1026 and actually even #1025. This requires more investigation!!
Reverts #1019.

Patch prefix caching to fix incorrect outputs

---

mistralrs-core/src/vision_models/idefics2/idefics2_input_processor.rs
mistralrs-core/src/vision_models/idefics3/inputs_processor.rs
mistralrs-core/src/vision_models/llava/llava_inputs_processor.rs
mistralrs-core/src/vision_models/llava/llava_next_inputs_processor.rs
mistralrs-core/src/vision_models/mllama/inputs_processor.rs
mistralrs-core/src/vision_models/phi3/phi3_inputs_processor.rs
mistralrs-core/src/vision_models/qwen2vl/inputs_processor.rs

The `DeviceMapper` was set to `None` for vision models before, now it's being passed properly. Tested working on Phi3V.

Fix paged attention for vision models on multiple devices

---

docs/DEVICE_MAPPING.md
mistralrs-core/src/pipeline/loaders/mod.rs
mistralrs-core/src/pipeline/loaders/vision_loaders.rs
mistralrs-core/src/pipeline/vision.rs
mistralrs-pyo3/mistralrs.pyi

- Correct the handling of activations from non mapped vs mapped
- Log the non-mapped sub models (only vision for now)
- Reduce defaults for easier useability

Improve automatic device map

---

mistralrs-core/src/lib.rs

The `block_in_place` function requires a multi-threaded runtime and will crash when executed in `CurrentThread` mode, which is the default for unit tests. While unit tests can be configured to run in multi-threaded mode, this is sometimes not practical or may require a significantly more complex setup, especially when tests involve tracing collectors.
With this change, the dummy run is skipped in single-threaded environments, simplifying the setup for unit tests.

Allow using library in CurrentThread runtime

---

mistralrs-core/src/pipeline/sampling.rs
mistralrs-core/src/response.rs
mistralrs-core/src/sequence.rs
mistralrs-core/src/tools/mod.rs
mistralrs-server/src/interactive_mode.rs
mistralrs/examples/simple_stream/main.rs
mistralrs/src/lib.rs

- Add `tool_calls` to `.chunk.delta` within `ChatCompletionChunkResponse` (i.e. `/v1/chat/completion` streaming). 
- This is done by checking whether the stream _could be_ parsed to the tool call structure (_could be_ meaning that we'd get an EOF, not a format error, when parsing it to a tool structure).

Allow chat streaming to use tools

---

README.md

There's currently an issue in the readme in this section:
> The build process will output a binary mistralrs-server at ./target/release/mistralrs-server which may be copied into the working directory with the following command:
>
> Example on Ubuntu:
> 
> cp ./target/release/mistralrs-server ./mistralrs-server
The intent here is to copy the `mistralrs-server` binary into the current working directory. Unfortunately, this doesn't work properly, as the repository already includes a directory with this name. The cp command copies the binary into that directory. Running subsequent examples fails because `./mistralrs-server` is a directory rather than the binary.
This PR updates the readme to suggest the user `cd` into `target/release` in order to access the binary.

Remove unexpected cp behavior

---

mistralrs-core/src/daemon.rs
mistralrs-core/src/pipeline/normal.rs
mistralrs-quant/src/distributed/socket.rs

core::ffi::c_char is defined as u8 instead of i8 in some platforms, so cannot use i8 as type in some codes.
fix https://github.com/EricLBuehler/mistral.rs/issues/1162

build fix for arm.

---

mistralrs-core/src/pipeline/diffusion.rs

Fix diffusion device mapping

---

mistralrs-server/src/chat_completion.rs
mistralrs-server/src/completions.rs

We were now 100% openai compliant for the streaming API.
https://platform.openai.com/docs/api-reference/completions/create
> If true, returns a stream of events that happen during the Run as server-sent events, terminating when the Run enters a terminal state with a data: [DONE] message.

Send [DONE] SSE chunk per openai spec

---

mistralrs-core/src/layers.rs
mistralrs-core/src/models/llama.rs
mistralrs-quant/build.rs
mistralrs-quant/kernels/rotary/cuda_compat.h
mistralrs-quant/kernels/rotary/rotary.cu
mistralrs-quant/src/lib.rs
mistralrs-quant/src/rotary/ffi.rs
mistralrs-quant/src/rotary/mod.rs

Now applied for both Q and K, also no .contiguous necessary when flash-attn.

Optimized CUDA RoPE kernels

---

mistralrs-pyo3/mistralrs.pyi

Fix typo in argument name: `add_speial_tokens` to `add_special_tokens`  
`got an unexpected keyword argument 'add_speial_tokens'`

Typo fix (add_speial_tokens to add_special_tokens)

---

mistralrs-core/src/models/deepseek2.rs
mistralrs-core/src/models/deepseek3.rs
mistralrs-core/src/ops.rs
mistralrs-quant/src/afq/ops.rs

Hi Eric,
I’d like to merge a recent PR made in [candle-vllm](https://github.com/EricLBuehler/candle-vllm/pull/124) into mistral.rs.
---
_Here are the comments from the original PR for your reference:_
The bincount operation takes a significant amount of time, especially with large token context sizes, leading to a slower moe_infer process. This PR replaces bincount with a Rust HashSet for counting expert appearances in topk_ids (produced by the Top-K operation or MoE gating), resulting in an overall inference performance improvement of over 20% for DeepSeek models.
Tested case (DeepSeek-V2-Chat)
Before:
```shell
Prompt "<｜begin▁of▁sentence｜>User: Talk about China.\n\nAssistant:"
Request cmpl-c934f6d3-02ac-48a5-bad3-e9d562ab92f1 with length 11 added to sequence group.
2025-04-10 05:55:13 …
```

Improve performance of deepseek models

---

mistralrs-core/src/models/deepseek2.rs
mistralrs-core/src/models/deepseek3.rs

This PR fixes a bug in the grouped top-k method (group_limited_greedy) in DeepSeek v2/v3 models.

Fix bug for group-topk (group_limited_greedy) in deepseek models

---

Cargo.lock
examples/python/lark.py
examples/python/lark_llg.py
mistralrs-core/Cargo.toml
mistralrs-core/src/engine/add_request.rs
mistralrs-core/src/engine/mod.rs
mistralrs-core/src/pipeline/diffusion.rs
mistralrs-core/src/pipeline/ggml.rs
mistralrs-core/src/pipeline/gguf.rs
mistralrs-core/src/pipeline/llg.rs
mistralrs-core/src/pipeline/mod.rs
mistralrs-core/src/pipeline/normal.rs
mistralrs-core/src/pipeline/sampling.rs
mistralrs-core/src/pipeline/speculative.rs
mistralrs-core/src/pipeline/vision.rs
mistralrs-core/src/sequence.rs

- this updates llguidance to 0.7.16 from crates.io - the openssl dep is now gone from `toktrie_hf_tokenizers`
- use `llguidance::Matcher` instead of Constraint - it has additional APIs and is generally cleaner
- use ParserFactory for building Matchers - this enables [slicer optimization](https://github.com/guidance-ai/llguidance/blob/main/docs/optimizations.md#slicer-optimization) and is anyway the only way to do it now
- use Matcher.validate_tokens() first, so we can often skip computing masks
- rework the spec-decoding code a bit
@EricLBuehler I need comments on the last bit (the rest should be uncontroversial) - I changed `sample_target_sequence_speculative()` to take draft tokens and stop sampling once it diverges, instead of sampling everything first and only dropping tokens later - …

update to llguidance 0.7.16

---

Cargo.lock
mistralrs-server/Cargo.toml
mistralrs-server/src/interactive_mode.rs

The io::stdin().read_line() cannot handle non-ascii input, which caused
crash when use backspace to delete non-ascii characters.
Introduce rustyline to the interactive mode to solve the problem. Plus
it can bring more editing features in the future.
Close #1140

Use rustyline to handle non-ascii in interactive mode

---

mistralrs-core/src/engine/logger.rs

The log enabler should be checked after the sleep instead of a busy
loop checking.
Since the interactive mode always disables the token speed logger, 100%
CPU was taken by this loop always.
(There is another busy loop problem which will be fixed in another PR.)

Fix CPU hogging in interactive mode

---

mistralrs-mcp/src/lib.rs

Fixes the `mistralrs-mcp/src/lib.rs` doctest:
```
---- mistralrs-mcp/src/lib.rs - (line 43) stdout ----
error[E0436]: functional record update syntax requires a struct
--> mistralrs-mcp/src/lib.rs:57:23
|
16 |                     ..Default::default()
|                       ^^^^^^^^^^^^^^^^^^
error[E0277]: the trait bound `McpServerSource: Default` is not satisfied
--> mistralrs-mcp/src/lib.rs:57:23
|
16 |                     ..Default::default()
|                       ^^^^^^^^^^^^^^^^^^ the trait `Default` is not implemented for `McpServerSource`
error: aborting due to 2 previous errors
```

Fix MCP doc test

---

Cargo.lock
Cargo.toml
mistralrs-core/src/gguf/gguf_tokenizer.rs

llguidance fixed the api breaking change from `tokenizers` in guidance-ai/llguidance#195, this PR updates the dependency on llguidance to the commit and version with the fix.
This however means that the locked version for tokenizers in the lockfile (0.21.1) is incompatible with llguidance. The two solutions to this (deleting the lockfile and updating tokenizers in mistral.rs dependency) are ultimately the same: tokenizers@0.21.2 ends up being used in mistral.rs, which funny enough introduces an API breaking change for `mistral-core` as well, the relevant change is:
```diff
$ git diff v0.21.1..v0.21.2 tokenizers/src/models/bpe/model.rs
diff --git a/tokenizers/src/models/bpe/model.rs b/tokenizers/src/models/bpe/model.rs
index 217c37e9..2f560b7e 100644
-pub type Vocab = HashMap<String, u32>; …
```

chore: update llguidance

---

mistralrs-core/src/vision_models/gemma3n/vision.rs

This change simplifies a logic expression triggering a needless bool warning and causing a CI failure.

Fix needless bool warning

---

examples/python/streaming.py

This change adjusts the streaming example to use a more modern and much smaller model. The example will still produce a coherent response, but it should be roughly 10x faster and require downloading one tenth as much model data.

Use smaller model in streaming example

---

examples/python/streaming.py

This change simplifies the Python streaming example output to display only the output as it is generated rather than printing the complete data structure returned along with each token.
For me, this change better aligns with my expectations of what output streaming from and LLM should look like in my terminal.

Simplify streaming example output

---

mistralrs-pyo3/generate_wheels.sh

This change adjusts the `mistralrs` Python package builds to target baseline "generic" CPUs on Linux rather than the native CPU of the build system. This should produce wheels with maximum CPU compatibility.
Prior to this change, CPUs lacking features found on the build system would not run the Python package properly and fail with an "Illegal Instruction" error message.
I have confirmed that this change fixes #1269 for me by building and installing the Python package from the current main branch using:
```sh
docker run --rm -v .:/io wheelmaker build --release -o wheels-cpu -m mistralrs-pyo3/Cargo.toml --interpreter python3.10
pip3 uninstall mistralrs
pip3 install wheels-cpu/mistralrs-0.6.0-cp310-cp310-manylinux_2_35_x86_64.whl
```
This fails with an "Illegal Instruction" error message. …

Target generic CPUs when building Python package
